version: '3.1'
services:

  py:
    container_name: visahack_scraper_py
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: visahack_scraper
    volumes:
      - .:/app
      - ./crontab:/etc/cron.daily/crontab

  db:
    container_name: visahack_scraper_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3390:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visahack_scraper 

    volumes:
      - visahack_scraper_db:/var/lib/mysql 
volumes:
  visahack_scraper_db: 
