apiVersion: batch/v1
kind: CronJob
metadata:
  name: visahack-scraper-cron
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: visahack-scrape
              image: ghcr.io/karintomania/visahack_scrape@sha256:837a379960e605c141d9575fe0b8c370eaff4cd5f1c68cda2be26d79898e9983
              imagePullPolicy: IfNotPresent
              # command:
              # - /bin/sh
              # - -c
              # - |
              #   tail -f /dev/null
              env:
                - name: DB_HOST
                  value: mysql
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: "root"
                - name: DB_NAME
                  value: "visahack_scraper"
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: visahack-secrets
                        key: mysql-password
          imagePullSecrets:
          - name: ghcr-io-cred
          restartPolicy: OnFailure
