apiVersion: batch/v1
kind: CronJob
metadata:
  name: visahack-scraper-cron
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: visahack-scrape
              image: ghcr.io/karintomania/visahack_scrape@sha256:252849029104c89742a76313bb2ff5e8b868cbe55d2d9d0354b3e238cc9a702e
              imagePullPolicy: IfNotPresent
              # command:
              # - /bin/sh
              # - -c
              # - |
              #   tail -f /dev/null
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
              env:
                - name: DB_HOST
                  value: mysql
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: "root"
                - name: DB_NAME
                  value: "visahack_scraper"
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: visahack-secrets
                        key: mysql-password
          imagePullSecrets:
          - name: ghcr-io-cred
          restartPolicy: OnFailure
          volumes:
          - emptyDir:
              medium: Memory
              sizeLimit: 256Mi
            name: cache-volume
