apiVersion: batch/v1
kind: CronJob
metadata:
  name: visahack-scraper-cron-get-jobs
  namespace: visahack-scraper
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: visahack-scrape
              image: ghcr.io/karintomania/visahack_scrape@sha256:624392b2c16fe6ff85473c2cb219fcef40c3e3b15b983eea3438c8a216fa0a7e
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - |
                mkdir -p ~/.ssh
                cp /etc/ssh-key/ssh-privatekey ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                # Start the SSH tunnel & keep it in the background
                ssh -o StrictHostKeyChecking=no -N -L 127.0.0.1:3306:localhost:3306 hideaki@46.101.1.52 &
                sleep 10
                sh /app/scripts/get_jobs.sh
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
              - mountPath: /etc/ssh-key
                name: ssh-key-secret
                readOnly: true
              env:
                - name: DB_HOST
                  value: localhost
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: "appuser"
                - name: DB_NAME
                  value: "visahack"
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: visahack-secrets
                        key: mysql-password
                - name: JOB_EXPIRED_DAYS
                  value: "30"
                - name: JOB_REMOVAL_DAYS
                  value: "90"
                - name: LINK_REMOVAL_DAYS
                  value: "30"
                - name: SLEEP_BETWEEN_URL
                  value: "10"
                - name: SLEEP_BETWEEN_DETAILS
                  value: "5"
                - name: SCRAPING_RETRY_ON_ERROR
                  value: "2"
          imagePullSecrets:
          - name: ghcr-io-cred
          restartPolicy: OnFailure
          volumes:
          - emptyDir:
              medium: Memory
              sizeLimit: 256Mi
            name: cache-volume
          - name: ssh-key-secret
            secret:
              secretName: ssh-key-secret

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: visahack-scraper-cron-expiration-check
  namespace: visahack-scraper
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: visahack-scrape
              image: ghcr.io/karintomania/visahack_scrape@sha256:624392b2c16fe6ff85473c2cb219fcef40c3e3b15b983eea3438c8a216fa0a7e
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - |
                mkdir -p ~/.ssh
                cp /etc/ssh-key/ssh-privatekey ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                # Start the SSH tunnel & keep it in the background
                ssh -o StrictHostKeyChecking=no -N -L 127.0.0.1:3306:localhost:3306 hideaki@46.101.1.52 &
                sleep 10
                sh /app/scripts/expiration_check.sh
              volumeMounts:
              - mountPath: /dev/shm
                name: cache-volume
              - mountPath: /etc/ssh-key
                name: ssh-key-secret
                readOnly: true
              env:
                - name: DB_HOST
                  value: localhost
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: "appuser"
                - name: DB_NAME
                  value: "visahack"
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: visahack-secrets
                        key: mysql-password
                - name: SLEEP_BETWEEN_URL
                  value: "10"
                - name: EXPIRATION_CHECK_FREQUENCY_DAYS
                  value: "3"
          imagePullSecrets:
          - name: ghcr-io-cred
          restartPolicy: OnFailure
          volumes:
          - emptyDir:
              medium: Memory
              sizeLimit: 256Mi
            name: cache-volume
          - name: ssh-key-secret
            secret:
              secretName: ssh-key-secret

