CREATE TABLE IF NOT EXISTS job_links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    origin VARCHAR(63) NOT NULL,
    url VARCHAR(2047) NOT NULL,
    country VARCHAR(8) NOT NULL,
    has_detail TINYINT(1) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    origin VARCHAR(63) NOT NULL,
    title VARCHAR(127) NOT NULL,
    company VARCHAR(127) NOT NULL,
    url VARCHAR(2047) NOT NULL,
    country VARCHAR(8) NOT NULL,
    salary VARCHAR(127),
    location VARCHAR(127),
    job_type VARCHAR(127) NOT NULL,
    description TEXT NOT NULL,
    active TINYINT(1) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
